component:
  prompt:
    - name
  base:
    template: .temples
    output: src/components
  temples:
    - template: component.hbs
      output: /{{ name }}/index.js
    - output: /{{ name }}/styles.module.scss
