component:
  prompt:
    - name
  base:
    template: .temples
    output: src/components
  temples:
    - template: component.js.hbs
      output: /{{ name }}/index.js
    - output: /{{ name }}/styles.module.scss

project:
  prompt:
    - name
    - description
  base:
    template: .temples
    output: src/content/projects
  temples:
    - template: project.mdx.hbs
      output: /{{ kebab name }}.mdx
